In [1]:
import numpy as np

In [4]:
array=np.arange(1,10)

In [5]:
array.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
array.astype('float64')

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
arr=np.round(array)

In [10]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr_1=np.arange(1,10)
arr_2=np.arange(11,20)

In [13]:
arr_sum = arr_1+arr_2

In [14]:
arr_sum

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [15]:
arr_2/arr_1

array([11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ,
        2.66666667,  2.42857143,  2.25      ,  2.11111111])