MODULE 2

DTYPE PARAMETER

In [1]:
import numpy as np


In [2]:
np.array([1,2,3,4],dtype=np.int32)

array([1, 2, 3, 4], dtype=int32)

In [3]:
np.array([1.5,2.9,3.7,4.5],dtype=np.float32)

array([1.5, 2.9, 3.7, 4.5], dtype=float32)

In [2]:
print("hello")

hello


ARANGE

In [3]:
empty_list=[]
for i in range(20):
    empty_list.append(i)
print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [10]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:

np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [11]:

np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [15]:
data=np.arange(1,17)
data.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [19]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
np.random.random((5,5))

array([[0.78875337, 0.71822603, 0.11315099, 0.8473095 , 0.26462208],
       [0.95094151, 0.13623901, 0.44084187, 0.42310669, 0.90408691],
       [0.56166393, 0.65264497, 0.52855404, 0.4778474 , 0.17496553],
       [0.51456752, 0.3480492 , 0.26638824, 0.74525831, 0.23991871],
       [0.16468766, 0.30017387, 0.25121654, 0.71920869, 0.37621941]])

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
arr=np.array([1,2,3])

In [28]:
arr

array([1, 2, 3])

In [29]:
arr.ndim

1

In [30]:
arrr=np.array([[1,2],[3,4]])

In [32]:
arrr

array([[1, 2],
       [3, 4]])

In [31]:
arrr.ndim

2

In [41]:
arrrr=np.array([[[1,2],[6,7]],[[3,4],[8,9]]])

In [39]:
arrrr

array([[[1, 2],
        [6, 7]],

       [[3, 4],
        [8, 9]]])

In [42]:
arrrr.ndim

3

In [43]:
arrrr.shape

(2, 2, 2)

In [44]:
arrrr.size

8

In [46]:
np.arange(1,5).size


4