In [1]:
import numpy as np

In [3]:
arr_1=np.arange(1,10).reshape(3,3)

In [4]:
arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.mean(arr_1)

np.float64(5.0)

In [6]:
np.mean(arr_1,axis=1)

array([2., 5., 8.])

In [7]:
np.mean(arr_1,axis=0)

array([4., 5., 6.])

In [9]:
np.std(arr_1)

np.float64(2.581988897471611)

In [11]:
np.median(arr_1)

np.float64(5.0)